### ISSUE TITLE
Better search performance

### ISSUE THREAD

**Issue by shaloo** [video-db/videodb-python#4]
### Confirm this is a new feature request

- [ ] Possible new feature in VideoDB Python Client
- [ ] Potential new feature in VideoDB API
- [X] I've checked the current issues, and there's no record of this feature request

### Describe the feature

Indexing is pretty slow.  Also the search feature is fairly slow. Any plans for faster response times?

### Describe the solution you'd like

Faster indexing and keyword search.

### Additional Context

Tried videodb to search some dev evangelist videos on youtub under 10 min to get shots of relevant sections - it took v v long beyond average response times.

**Comment by ashish-spext** [comment]
Hi @shaloo thank you for the feedback.

1 - For faster indexing there is one improvement that is soon going to get shipped in the next version along with some other exciting features, please stay tuned.

2 - For searching can you share how much time it is taking in your case?
Searching for now is optimized to take around 1 to 2 seconds irrespective of the video length (video.search) or cumulative video length of collection  (collection.search).

So even if you have multiple hours of video / videos in collection VideoDB should return the relevant clip in seconds only.

Sample snippet to test search latency in collection:

```
import time
import videodb

from statistics import mean
from dotenv import load_dotenv
load_dotenv()

# VIDEO_DB_API_KEY is set in .env and loaded by dotenv
conn = videodb.connect()
default_collection = conn.get_collection()
queries = ["scense from decades apart"]
# queries for https://www.youtube.com/watch?v=kmvvA7wudKo uncomment below section if video is not in collection
"""
print("uploading video")
video = default_collection.upload(url="https://www.youtube.com/watch?v=kmvvA7wudKo")
print(f"'{video.name}' video uploaded")
print(f"'{video.name}' starting indexing")
video.index_spoken_words()
print(f"'{video.name}' video indexed")
"""
search_latencies = []
iterations = 5

for i in range(1, iterations+1):
    print(f"Testing the search latency - iteration #{i}")
    for query in queries:
        start = time.time()
        search_results = default_collection.search(query)
        duration = time.time() - start
        search_latencies.append(duration)
        print(f"query '{query}' took {duration} seconds")
    print("-------")

print(f"Average query response time: {mean(search_latencies)}")
```
Results should be similar for single video and can be tested by replacing `default_collection.search(query)` to `video.search(query)` in above snippet.

**Comment by ashish-spext** [comment]
Hey @shaloo can you upgrade to 0.0.3 and check the performance now?
There should be loader on indexing to show the progress.
Here are some of the other updates - https://docs.videodb.io/version-0-0-3-timeline-and-assets-44

**Comment by ashish-spext** [comment]
Closing this issue for now, please let us know in case of any additional feedback on new version performance.
